#pragma once

//
// This file contains all IDs of game assets 
// FORMAT regionId(1) miscId(2) ani(2) sprite(2)
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20

// CHARACTER
#define OBJECT_TYPE_MARIO	101
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3

// MISCS
#define OBJECT_TYPE_COIN 201
#define OBJECT_TYPE_MUSHROOM 203
#define OBJECT_TYPE_GREEN_MUSHROOM 204
#define OBJECT_TYPE_QUESTION_BLOCK 205

// HUD
#define OBJECT_TYPE_POINT 401
#define OBJECT_TYPE_ITEM_BOX 402
#define OBJECT_TYPE_FONT 403

//INVISIBLES
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_PORTAL	50

//ID: 0
#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT 1010001
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT 1010002

#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT 1010003
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT 1010004
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT 1010005	1010006
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT 1010007	1010008

#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT 1010009
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT 1010011

//ANIMATION
#define ID_ANI_MARIO_SMALL_IDLE_LEFT 1010100
#define ID_ANI_MARIO_SMALL_IDLE_RIGHT 1010200

#define ID_ANI_MARIO_SMALL_WALKING_LEFT 1010300
#define ID_ANI_MARIO_SMALL_WALKING_RIGHT 1010400

#define ID_ANI_MARIO_SMALL_RUNNING_LEFT 1010500
#define ID_ANI_MARIO_SMALL_RUNNING_RIGHT 1010600

#define ID_ANI_MARIO_SMALL_BRACE_LEFT 1010700
#define ID_ANI_MARIO_SMALL_BRACE_RIGHT 1010800

#define ID_ANI_MARIO_SMALL_BRACE_WALK_LEFT 1010900
#define ID_ANI_MARIO_SMALL_BRACE_WALK_RIGHT 1011000

#pragma endregion 

#define ID_SPRITE_BRICK 20000

#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)

#define ID_SPRITE_CLOUD 50000
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD+1000)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD+2000)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD+3000)

//ID: 2
#pragma region MISC 
//COIN
#define ID_ANI_COIN 2010101

//MUSHROOM
#define ID_ANI_MUSHROOM 2030101

//GREEN MUSHROOM
#define ID_ANI_GREEN_MUSHROOM 2040101

//QUESTION BLOCK
#define ID_ANI_QUESTION_BLOCK_IDLE 2050100
#define ID_ANI_QUESTION_BLOCK_OPENED 2050200

#pragma endregion 


//ID: 4
#pragma region HUD 

//POINT
#define ID_SPRITE_POINT_100 4010001
#define ID_SPRITE_POINT_200 4010002
#define ID_SPRITE_POINT_400 4010003
#define ID_SPRITE_POINT_800 4010004
#define ID_SPRITE_POINT_1000 4010005
#define ID_SPRITE_POINT_2000 4010006
#define ID_SPRITE_POINT_4000 4010007
#define ID_SPRITE_POINT_8000 4010008
#define ID_SPRITE_POINT_UP 4010009

//ITEM BOX
#define ID_SPRITE_ITEM_BOX_EMPTY 4020001
#define ID_SPRITE_ITEM_BOX_MUSHROOM 4020002
#define ID_SPRITE_ITEM_BOX_FLOWER 4020003
#define ID_SPRITE_ITEM_BOX_STAR 4020004

//FONT
#define ID_SPRITE_FONT_0 4030001
#define ID_SPRITE_FONT_1 4030002
#define ID_SPRITE_FONT_2 4030003
#define ID_SPRITE_FONT_3 4030004
#define ID_SPRITE_FONT_4 4030005
#define ID_SPRITE_FONT_5 4030006
#define ID_SPRITE_FONT_6 4030007
#define ID_SPRITE_FONT_7 4030008
#define ID_SPRITE_FONT_8 4030009
#define ID_SPRITE_FONT_9 4030010

#define ID_SPRITE_FONT_PLAY_CHARACTER 4030011
#define ID_SPRITE_FONT_ARROW_WHITE 4030012
#define ID_SPRITE_FONT_P_WHITE 4030013
#define ID_SPRITE_FONT_ARROW_BLACK 4030014
#define ID_SPRITE_FONT_P_BLACK 4030015

//GAME BOARD
#define ID_SPRITE_BOARD_BACKGROUND 4040001
#define ID_SPRITE_BOARD_UI 4040002

#pragma endregion 